import { CommonModule } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../../../../core/services/auth.service';
import { FinanceService, FinancialEntry, FinancialEntryInput, FinancialEntryStatus, FinancialEntryType, FinancialSummary } from '../../../../core/services/finance.service';

@Component({
  selector: 'app-finance-page', standalone: true, imports: [CommonModule, FormsModule],
  template: `
    <div class="admin-header finance-header"><div><span class="eyebrow">Gestão financeira</span><h1>Financeiro</h1><p>Controle vencimentos, recebimentos e notas fiscais de entrada.</p></div><button class="button" *ngIf="auth.canWrite('finance')" (click)="openNew()">+ Novo lançamento</button></div>
    <section class="finance-stats" *ngIf="summary">
      <article><span>A pagar</span><strong>{{ money(summary.payablePending) }}</strong><small>Em aberto</small></article>
      <article><span>A receber</span><strong>{{ money(summary.receivablePending) }}</strong><small>Em aberto</small></article>
      <article><span>Pago no mês</span><strong>{{ money(summary.paidThisMonth) }}</strong><small>Saídas realizadas</small></article>
      <article><span>Recebido no mês</span><strong>{{ money(summary.receivedThisMonth) }}</strong><small>Entradas realizadas</small></article>
      <article class="attention"><span>Vencidos</span><strong>{{ summary.overdueCount }}</strong><small>Pedem atenção</small></article>
    </section>
    <nav class="finance-tabs" aria-label="Tipos de lançamento">
      <button *ngFor="let tab of tabs" [class.active]="activeType === tab.type" (click)="selectType(tab.type)">{{ tab.label }}</button>
    </nav>
    <section class="form-card finance-filters"><input class="form-control" [(ngModel)]="search" placeholder="Buscar descrição, pessoa ou documento"><select class="form-control" [(ngModel)]="statusFilter"><option value="">Todos os status</option><option value="pending">Pendente</option><option value="paid">Pago/recebido</option><option value="overdue">Vencido</option><option value="cancelled">Cancelado</option></select></section>
    <section class="system-alert loading" *ngIf="loading"><span class="spinner"></span><div><strong>Carregando financeiro</strong><p>Buscando os lançamentos mais recentes.</p></div></section>
    <section class="system-alert error" *ngIf="error" role="alert"><span class="alert-icon">!</span><div><strong>Não foi possível carregar</strong><p>{{ error }}</p></div><button class="button-ghost" (click)="load()">Tentar novamente</button></section>
    <section class="form-card table-card" *ngIf="!loading && !error">
      <table><thead><tr><th>Descrição</th><th>{{ activeType === 'receivable' ? 'Cliente' : 'Fornecedor' }}</th><th>Vencimento</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead>
      <tbody><tr *ngFor="let entry of filteredEntries()"><td><strong>{{ entry.description }}</strong><br><small>{{ entry.documentNumber || entry.category || 'Sem documento' }}</small></td><td>{{ entry.customer || entry.supplier || '—' }}</td><td>{{ date(entry.dueDate) }}</td><td><strong>{{ money(entry.amount) }}</strong></td><td><span class="badge" [class.success]="entry.status === 'paid'" [class.danger]="isOverdue(entry)">{{ statusLabel(entry) }}</span></td><td class="table-actions"><button class="button-ghost" (click)="edit(entry)" *ngIf="auth.canWrite('finance')">Editar</button><button class="button-danger" (click)="remove(entry)" *ngIf="auth.canWrite('finance')">Excluir</button></td></tr>
      <tr *ngIf="!filteredEntries().length"><td colspan="6" class="finance-empty">Nenhum lançamento encontrado nesta seção.</td></tr></tbody></table>
    </section>
    <div class="modal-backdrop" *ngIf="showForm" (click)="closeForm()"><section class="modal-panel finance-modal" (click)="$event.stopPropagation()" role="dialog" aria-modal="true">
      <div class="admin-header"><div><h2>{{ editingId ? 'Editar lançamento' : titleFor(form.type) }}</h2><p>Preencha os dados para manter o fluxo financeiro atualizado.</p></div><button class="button-ghost" (click)="closeForm()">Fechar</button></div>
      <div class="form-grid three"><div class="form-field"><label>Tipo</label><select class="form-control" [(ngModel)]="form.type"><option value="payable">Conta a pagar</option><option value="receivable">Conta a receber</option><option value="supplier_invoice">Nota fiscal de entrada</option></select></div><div class="form-field span-two"><label>Descrição *</label><input class="form-control" [(ngModel)]="form.description"></div>
      <div class="form-field"><label>Valor *</label><input class="form-control" type="number" min="0.01" step="0.01" [(ngModel)]="form.amount"></div><div class="form-field"><label>Vencimento *</label><input class="form-control" type="date" [(ngModel)]="form.dueDate"></div><div class="form-field"><label>Competência</label><input class="form-control" type="date" [(ngModel)]="form.competenceDate"></div>
      <div class="form-field"><label>Status</label><select class="form-control" [(ngModel)]="form.status"><option value="pending">Pendente</option><option value="paid">Pago/recebido</option><option value="overdue">Vencido</option><option value="cancelled">Cancelado</option></select></div><div class="form-field"><label>Data do pagamento</label><input class="form-control" type="date" [(ngModel)]="form.paymentDate" [disabled]="form.status !== 'paid'"></div><div class="form-field"><label>Categoria</label><input class="form-control" [(ngModel)]="form.category" placeholder="Ex.: Insumos"></div>
      <div class="form-field" *ngIf="form.type !== 'receivable'"><label>Fornecedor *</label><input class="form-control" [(ngModel)]="form.supplier"></div><div class="form-field" *ngIf="form.type === 'receivable'"><label>Cliente</label><input class="form-control" [(ngModel)]="form.customer"></div><div class="form-field"><label>Número do documento</label><input class="form-control" [(ngModel)]="form.documentNumber"></div><div class="form-field" *ngIf="form.type === 'supplier_invoice'"><label>Chave de acesso da NF-e</label><input class="form-control" maxlength="44" [(ngModel)]="form.accessKey"></div><div class="form-field span-all"><label>Observações</label><textarea class="form-control" [(ngModel)]="form.notes"></textarea></div></div>
      <p class="form-feedback" *ngIf="formError">{{ formError }}</p><div class="form-actions"><button class="button" [disabled]="saving" (click)="save()">{{ saving ? 'Salvando...' : 'Salvar lançamento' }}</button><button class="button-ghost" (click)="closeForm()">Cancelar</button></div>
    </section></div>
  `,
  styles: [`
    .finance-header{align-items:flex-end}.finance-stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-bottom:20px}.finance-stats article{padding:18px;border:1px solid var(--admin-line);border-radius:18px;background:var(--admin-surface);box-shadow:var(--admin-shadow-sm)}.finance-stats span,.finance-stats small{display:block;color:var(--admin-muted)}.finance-stats strong{display:block;margin:8px 0;font-size:1.35rem}.finance-stats .attention strong{color:var(--color-danger)}.finance-tabs{display:flex;gap:8px;margin-bottom:14px;overflow:auto}.finance-tabs button{border:1px solid var(--admin-line);border-radius:999px;padding:11px 16px;background:#fff;color:var(--admin-muted);font-weight:700;white-space:nowrap}.finance-tabs button.active{background:var(--admin-brand);color:#fff;border-color:var(--admin-brand)}.finance-filters{display:grid;grid-template-columns:1fr 220px;gap:12px;padding:14px}.finance-empty{text-align:center;padding:36px;color:var(--admin-muted)}.finance-modal{width:min(960px,100%)}.finance-modal h2{margin:0}.span-two{grid-column:span 2}.span-all{grid-column:1/-1}.form-feedback{color:var(--color-danger)}@media(max-width:1100px){.finance-stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:720px){.finance-stats,.finance-filters,.form-grid.three{grid-template-columns:1fr}.span-two{grid-column:auto}.finance-header{align-items:flex-start;flex-direction:column}}
  `]
})
export class FinancePageComponent implements OnInit {
  readonly auth = inject(AuthService); private readonly finance = inject(FinanceService);
  readonly tabs = [{ type: 'payable' as const, label: 'Contas a pagar' }, { type: 'receivable' as const, label: 'Contas a receber' }, { type: 'supplier_invoice' as const, label: 'Notas fiscais de entrada' }];
  activeType: FinancialEntryType = 'payable'; entries: FinancialEntry[] = []; summary: FinancialSummary | null = null; loading = true; error = ''; search = ''; statusFilter = ''; showForm = false; saving = false; formError = ''; editingId: string | null = null; form = this.blankForm();
  private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  ngOnInit() { this.activeType = this.route.snapshot.data['financeType'] || 'payable'; void this.load(); }
  async load() { this.loading = true; this.error = ''; try { [this.entries, this.summary] = await Promise.all([this.finance.list(this.activeType), this.finance.summary()]); } catch (error) { this.error = error instanceof Error ? error.message : 'Erro inesperado.'; } finally { this.loading = false; } }
  selectType(type: FinancialEntryType) { const segment = type === 'payable' ? 'contas-a-pagar' : type === 'receivable' ? 'contas-a-receber' : 'notas-fiscais-entrada'; void this.router.navigate(['/admin/financeiro', segment]); }
  blankForm(type = this.activeType): FinancialEntryInput { const today = new Date().toISOString().slice(0, 10); return { type, description: '', amount: 0, dueDate: today, competenceDate: today, paymentDate: null, status: 'pending', category: null, supplier: null, customer: null, documentNumber: null, accessKey: null, notes: null }; }
  openNew() { this.editingId = null; this.form = this.blankForm(); this.formError = ''; this.showForm = true; }
  edit(entry: FinancialEntry) { this.editingId = entry.id; this.form = { type: entry.type, description: entry.description, amount: entry.amount, dueDate: entry.dueDate, competenceDate: entry.competenceDate, paymentDate: entry.paymentDate, status: entry.status, category: entry.category, supplier: entry.supplier, customer: entry.customer, documentNumber: entry.documentNumber, accessKey: entry.accessKey, notes: entry.notes }; this.showForm = true; }
  closeForm() { if (!this.saving) this.showForm = false; }
  async save() { if (!this.form.description.trim() || !this.form.dueDate || this.form.amount <= 0) { this.formError = 'Preencha descrição, valor e vencimento.'; return; } if (this.form.type === 'supplier_invoice' && !this.form.supplier?.trim()) { this.formError = 'Informe o fornecedor da nota fiscal.'; return; } this.saving = true; this.formError = ''; try { this.form.paymentDate = this.form.status === 'paid' ? (this.form.paymentDate || new Date().toISOString().slice(0, 10)) : null; if (this.editingId) await this.finance.update(this.editingId, this.form); else await this.finance.create(this.form); this.activeType = this.form.type; this.showForm = false; await this.load(); } catch (error) { this.formError = error instanceof Error ? error.message : 'Erro ao salvar.'; } finally { this.saving = false; } }
  async remove(entry: FinancialEntry) { if (!confirm(`Excluir "${entry.description}"?`)) return; try { await this.finance.remove(entry.id); await this.load(); } catch (error) { alert(error instanceof Error ? error.message : 'Erro ao excluir.'); } }
  filteredEntries() { const term = this.search.trim().toLowerCase(); return this.entries.filter((entry) => (!this.statusFilter || entry.status === this.statusFilter) && (!term || [entry.description, entry.supplier, entry.customer, entry.documentNumber].some((value) => value?.toLowerCase().includes(term)))); }
  isOverdue(entry: FinancialEntry) { return entry.status === 'overdue' || (entry.status === 'pending' && entry.dueDate < new Date().toISOString().slice(0, 10)); }
  statusLabel(entry: FinancialEntry) { if (this.isOverdue(entry)) return 'Vencido'; return ({ pending: 'Pendente', paid: entry.type === 'receivable' ? 'Recebido' : 'Pago', cancelled: 'Cancelado', overdue: 'Vencido' } as Record<FinancialEntryStatus, string>)[entry.status]; }
  titleFor(type: FinancialEntryType) { return type === 'payable' ? 'Nova conta a pagar' : type === 'receivable' ? 'Nova conta a receber' : 'Nova nota fiscal de entrada'; }
  money(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value || 0); }
  date(value: string) { return new Intl.DateTimeFormat('pt-BR', { timeZone: 'UTC' }).format(new Date(`${value}T12:00:00Z`)); }
}
